# Fichier de configuration!

directory: ~/Videos
videos:
  - uri: MVI_1208.MOV
    duration: 12.0
  - uri: MVI_1212.MOV
    duration: 5.0
  - uri: MVI_1213.MOV
    duration: 10.0
  - uri: MVI_1214.MOV
    duration: 10.0
  - uri: MVI_1217.MOV
    duration: 10.0
  - uri: MVI_1219.MOV
    duration: 10.0
  - uri: MVI_1220.MOV
    duration: 10.0
  - uri: MVI_1224.MOV
    duration: 10.0
